# Generated by Django 6.0.3 on 2026-05-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hint_nom_reference',
            field=models.CharField(blank=True, default='', help_text="Affichée sur le formulaire d'annonce (ex. marque pour une voiture).", max_length=255, verbose_name='Aide pour le nom lié à la catégorie'),
        ),
        migrations.AddField(
            model_name='property',
            name='nom_reference_categorie',
            field=models.CharField(blank=True, default='', help_text='Ex. marque/modèle pour une voiture, nom de résidence pour un appartement.', max_length=250, verbose_name='Nom selon la catégorie'),
        ),
        migrations.AlterField(
            model_name='property',
            name='titre',
            field=models.CharField(help_text='Nom visible de votre objet (ex. « Location weekend »).', max_length=250, verbose_name="Nom de l'annonce"),
        ),
    ]
