# Generated by Django 6.0.3 on 2026-05-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_contrat_date_confirmation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
