# Generated by Django 6.0.3 on 2026-05-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_delete_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_by_staff',
            field=models.BooleanField(default=False, help_text='True si la réservation a été créée depuis l’interface administrateur.', verbose_name='Créée par le staff'),
        ),
    ]
