# Generated by Django 6.0.4 on 2026-05-03 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_initial'),
        ('reservations', '0002_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avis',
            name='cible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avis',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signalement',
            name='objet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('auteur', 'reservation')},
        ),
    ]
