# Generated by Django 6.0.3 on 2026-05-03 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0004_delete_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Payé'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('numero_facture', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='reservations.reservation')),
            ],
        ),
    ]
