# Generated by Django 6.0.4 on 2026-05-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='identity_document',
            field=models.ImageField(blank=True, null=True, upload_to='identity_documents/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identity_document_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
